[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_reward = "E9yxiWvqXm76keKtxZ5MFQpdpJfDJThgvX85tpVWdzPQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mehran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
